In [1]:
import os
import ray
import numpy as np
import pandas as pd
from typing import List
from utils.data import load_yaml
from imaris.imaris import ImarisDataObject
from parsers.surface_track_id_parser import SurfaceObjectTrackParserDistributed
import time

In [2]:
#ims_file = "/home/shehan/Documents/projects/nih/nih_parsers/data/temp_test/Ex112-mitotrackerred-B6-BALB-050125_batch_TileScan_1_BALB-US-Position_3_(0).ims"
ims_file = "/home/shehan/Documents/projects/nih/nih_parsers/data/tracks/GFP #1 Sec2 Roi1 2x2 1h30min.ims"
parser = SurfaceObjectTrackParserDistributed(ims_file_path=ims_file)
ims = ImarisDataObject(ims_file)
data = ims.data

In [3]:
out = parser.inspect(0)

In [4]:
f = out["final_df"]
f2 = out["final_df2"]
f.equals(f2)

True

In [5]:
f

,Acceleration,Acceleration X,Acceleration Y,Acceleration Z,Area,BoundingBoxAA Length X,BoundingBoxAA Length Y,BoundingBoxAA Length Z,BoundingBoxOO Length A,BoundingBoxOO Length B,...,Time Since Track Start,Velocity Angle X,Velocity Angle Y,Velocity Angle Z,Velocity X,Velocity Y,Velocity Z,Volume,Object_ID,Track_ID
0,0.0,0.0,0.0,0.0,258.658295,12.742188,8.191406,21.677090,6.519531,10.185547,...,0.000000,22.638807,85.694168,67.822632,0.009740,0.000793,0.003984,220.409760,0,1000000000
1,0.0,0.0,0.0,0.0,212.222092,9.101562,6.367188,21.677088,5.977051,9.023438,...,0.000000,91.397850,66.206337,156.163025,-0.000396,0.006569,-0.014891,180.325333,1,1000000001
3,0.0,0.0,0.0,0.0,4560.166992,19.109375,31.847656,50.579872,18.164062,31.980469,...,0.000000,88.710564,13.329387,76.738335,0.000736,0.031768,0.007490,7744.690918,3,1000000003
5,0.0,0.0,0.0,0.0,389.386017,9.097656,8.187500,28.902786,7.980469,8.191406,...,0.000000,92.653938,39.591362,50.536152,-0.001403,0.023373,0.019278,333.774933,5,1000000005
6,0.0,0.0,0.0,0.0,3863.962646,19.109375,26.390625,50.579872,18.789062,25.941406,...,0.000000,126.485489,58.616585,127.780983,-0.015516,0.013591,-0.015986,6017.525879,6,1000000006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
224773,0.0,0.0,0.0,0.0,760.185852,15.468750,10.921875,28.902786,11.477539,14.984375,...,965.471985,20.490808,101.111961,106.995766,0.025937,-0.005335,-0.008092,1023.777832,224773,1000207718
224774,0.0,0.0,0.0,0.0,565.666321,7.281250,9.101562,43.354179,5.871094,8.015625,...,2208.010986,51.707245,88.227013,38.351952,0.010216,0.000511,0.012928,527.219666,224774,1000185394
224775,0.0,0.0,0.0,0.0,749.466248,10.011719,12.738281,28.902786,8.847656,12.023438,...,5452.555176,76.574844,95.441528,14.525982,0.002781,-0.001135,0.011593,1275.807129,224775,1000001656
224776,0.0,0.0,0.0,0.0,393.100128,8.191406,8.191406,36.128483,6.773438,6.609375,...,5452.555176,85.072235,73.843842,16.933987,0.002384,0.007719,0.026533,357.535187,224776,1000001660
224777,0.0,0.0,0.0,0.0,356.998108,9.101562,8.191406,28.902786,5.677734,8.242188,...,2276.741943,86.768112,72.489494,162.176819,0.000341,0.001816,-0.005746,366.749878,224777,1000184152

In [3]:
np.array(data.get("Scene8").get("Content").get("MegaSurfaces0").get("SurfaceModel"))

array([( 0,      0, 4, 14,  9, 3, 57298.11 , 38201.29 , 25.289936, 57310.85 , 38209.48 , 46.967026, 8, 0.50006104,      0,      4,      0,      4),
       ( 0,      1, 4, 10,  7, 3, 57239.87 , 38252.25 , -3.612848, 57248.973, 38258.617, 18.06424 , 8, 0.50006104,      4,      8,      4,      8),
       ( 0,      3, 6, 21, 35, 7, 57325.41 , 38068.434, -3.612848, 57344.52 , 38100.28 , 46.967026, 8, 0.50006104,      8,     14,      8,     14),
       ...,
       (79, 224775, 4, 11, 14, 4, 56499.145, 37454.195, 10.838544, 56509.156, 37466.934, 39.74133 , 8, 0.50006104, 437537, 437541, 437537, 437541),
       (79, 224776, 4,  9,  9, 5, 56485.496, 37457.832, 10.838544, 56493.688, 37466.023, 46.967026, 8, 0.50006104, 437541, 437545, 437541, 437545),
       (79, 224777, 4, 10,  9, 4, 56481.855, 37459.652, 18.06424 , 56490.957, 37467.844, 46.967026, 8, 0.50006104, 437545, 437549, 437545, 437549)],
      dtype=[('ID_Time', '<i8'), ('ID', '<i8'), ('NumberOfLevels', '<i8'), ('SizeX', '<i8'), ('SizeY', '<i8'), ('SizeZ', '<i8'), ('ExtendMinX', '<f4'), ('ExtendMinY', '<f4'), ('ExtendMinZ', '<f4'), ('ExtendMaxX', '<f4'), ('ExtendMaxY', '<f4'), ('ExtendMaxZ', '<f4'), ('DataCountPerChildNode', '<i8'), ('Threshold', '<f4'), ('LevelInfoBegin', '<i8'), ('LevelInfoEnd', '<i8'), ('BlockInfoBegin', '<i8'), ('BlockInfoEnd', '<i8')])

In [4]:
np.array(data.get("Scene8").get("Content").get("MegaSurfaces0").get("TrackObject0"))

array([(     0,), (  1663,), (126093,), ..., (224617,), (222357,),
       (224722,)], dtype=[('ID_Object', '<i8')])

In [5]:
object_ids = pd.DataFrame(np.asarray(data.get("Scene8").get("Content").get("MegaSurfaces0").get("TrackObject0")))
object_ids

        ID_Object
0               0
1            1663
2          126093
3          127410
4          129979
...           ...
101184     222245
101185     223437
101186     224617
101187     222357
101188     224722

[101189 rows x 1 columns]

In [12]:
stats_id_objects = pd.DataFrame(np.asarray(data.get("Scene8").get("Content").get("MegaSurfaces0").get("StatisticsValue")))
stats_id_objects

          ID_Time  ID_Object  ID_StatisticsType         Value
0              -1         -1                  5  2.783000e+03
1              -1         -1                  6  1.011890e+05
2              -1         -1                  7  1.011890e+05
3              -1         -1                  8  8.234778e+07
4              -1         -1                  9  2.437183e+07
...           ...        ...                ...           ...
13951570       79     224428              26291  2.075231e+02
13951571       79     224510              26291  6.038209e+02
13951572       79     224560              26291  3.067408e+02
13951573       79     224617              26291  1.227466e+03
13951574       79     224722              26291  5.689697e+02

[13951575 rows x 4 columns]

In [14]:
np.unique(stats_id_objects["ID_Object"]).shape

(103973,)

In [9]:
np.unique(object_ids).shape

(101189,)

In [19]:
stats_id_objects["ID_Object"]

0               -1
1               -1
2               -1
3               -1
4               -1
             ...
13951570    224428
13951571    224510
13951572    224560
13951573    224617
13951574    224722
Name: ID_Object, Length: 13951575, dtype: int64

In [19]:
object_ids = pd.DataFrame(np.asarray(data.get("Scene8").get("Content").get("MegaSurfaces0").get("StatisticsValue")))
object_ids

          ID_Time  ID_Object  ID_StatisticsType         Value
0              -1         -1                  5  2.783000e+03
1              -1         -1                  6  1.011890e+05
2              -1         -1                  7  1.011890e+05
3              -1         -1                  8  8.234778e+07
4              -1         -1                  9  2.437183e+07
...           ...        ...                ...           ...
13951570       79     224428              26291  2.075231e+02
13951571       79     224510              26291  6.038209e+02
13951572       79     224560              26291  3.067408e+02
13951573       79     224617              26291  1.227466e+03
13951574       79     224722              26291  5.689697e+02

[13951575 rows x 4 columns]

In [20]:
trackinfo = pd.DataFrame(np.asarray(data.get("Scene8").get("Content").get("MegaSurfaces0").get("Track0")))
trackinfo

,ID,IndexTrackObjectBegin,IndexTrackObjectEnd,IndexTrackEdgeBegin,IndexTrackEdgeEnd
0,1000000000,0,36,0,35
1,1000000001,36,43,35,41
2,1000000003,43,123,41,120
3,1000000005,123,127,120,123
4,1000000006,127,130,123,125
...,...,...,...,...,...
2778,1000222046,101175,101178,98397,98399
2779,1000222137,101178,101181,98399,98401
2780,1000222184,101181,101184,98401,98403
2781,1000222245,101184,101187,98403,98405
2782,1000222357,101187,101189,98405,98406

In [20]:
track_ids = pd.DataFrame(np.asarray(data.get("Scene8").get("Content").get("MegaSurfaces0").get("Track0")))["ID"]

In [53]:
track_ids

0       1000000000
1       1000000001
2       1000000003
3       1000000005
4       1000000006
           ...
2778    1000222046
2779    1000222137
2780    1000222184
2781    1000222245
2782    1000222357
Name: ID, Length: 2783, dtype: int64

In [36]:
obids = stats_id_objects["ID_Object"]
obids

0               -1
1               -1
2               -1
3               -1
4               -1
             ...
13951570    224428
13951571    224510
13951572    224560
13951573    224617
13951574    224722
Name: ID_Object, Length: 13951575, dtype: int64

In [43]:
stats_id_objects[~stats_id_objects["ID_Object"].isin(track_ids)]

          ID_Time  ID_Object  ID_StatisticsType         Value
0              -1         -1                  5  2.783000e+03
1              -1         -1                  6  1.011890e+05
2              -1         -1                  7  1.011890e+05
3              -1         -1                  8  8.234778e+07
4              -1         -1                  9  2.437183e+07
...           ...        ...                ...           ...
13951570       79     224428              26291  2.075231e+02
13951571       79     224510              26291  6.038209e+02
13951572       79     224560              26291  3.067408e+02
13951573       79     224617              26291  1.227466e+03
13951574       79     224722              26291  5.689697e+02

[13660680 rows x 4 columns]

In [ ]:
TrackSegment0

In [ ]:
out = parser.inspect(0)

In [ ]:
f = out["stats_df"]
f2 = out["stats_df2"]
f.equals(f2)