In [1]:
import os
import ray
import numpy as np
import pandas as pd
from typing import List
from utils.data import load_yaml
from imaris.imaris import ImarisDataObject
from parsers.track_parser import TrackParserDistributed
import time

In [2]:
#ims_file = "/home/shehan/Documents/projects/nih/nih_parsers/data/temp_test/Ex112-mitotrackerred-B6-BALB-050125_batch_TileScan_1_BALB-US-Position_3_(0).ims"
ims_file = "/home/shehan/Documents/projects/nih/nih_parsers/data/tracks/GFP #1 Sec2 Roi1 2x2 1h30min.ims"
parser = TrackParserDistributed(ims_file_path=ims_file)
data = ImarisDataObject(ims_file).data

In [3]:
out = parser.inspect(0)

In [4]:
f = out["final_df"]
f2 = out["final_df2"]
f.equals(f2)

True

In [5]:
f

,Track Ar1 Mean,Track Ar1 X,Track Ar1 Y,Track Ar1 Z,Track Area Mean,Track Center of Homogeneous Mass X,Track Center of Homogeneous Mass Y,Track Center of Homogeneous Mass Z,Track Center of Image Mass X Channel_1,Track Center of Image Mass X Channel_2,...,Track Shortest Distance to Surfaces Min_Surfaces Unnamed 4 CG.GC.C-.G-.icsx_[ibrx_2023-09-27T11-04-45.364],Track Speed Max,Track Speed Mean,Track Speed Min,Track Speed StdDev,Track Speed Variation,Track Sphericity Mean,Track Straightness,Track Volume Mean,Track_ID
1000000000,-0.550184,-0.591558,-0.706574,-0.352421,184.048630,57305.355469,38205.421875,38.931080,57305.492188,57305.222656,...,58.586376,0.041609,0.022603,0.010553,0.007755,0.343085,0.730995,0.027259,145.742294,1000000000
1000000001,-0.476468,-0.305364,-0.885106,-0.238933,173.122635,57245.156250,38255.199219,4.065064,57245.222656,57245.167969,...,81.714478,0.026032,0.021547,0.016280,0.003183,0.147718,0.785525,0.140231,149.012894,1000000001
1000000003,-0.451769,-0.417780,-0.491516,-0.446013,3441.188721,57338.707031,38082.734375,26.736328,57339.503906,57338.050781,...,22.588594,0.072173,0.027683,0.010563,0.011372,0.410796,0.426913,0.035962,5119.760742,1000000003
1000000005,0.461317,0.605533,0.359849,0.418570,340.100220,57337.539062,38049.863281,37.823231,57337.769531,57338.199219,...,7.265651,0.030330,0.019375,0.015690,0.005034,0.259816,0.641248,0.401058,328.207428,1000000005
1000000006,NaN,NaN,NaN,NaN,3731.450195,57325.714844,38074.410156,23.871647,57325.816406,57325.382812,...,19.686106,0.040204,0.033214,0.026096,0.004988,0.150175,0.381708,0.937294,5147.984375,1000000006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000222046,NaN,NaN,NaN,NaN,179.472153,56780.675781,37800.671875,39.741333,56780.726562,56780.429688,...,42.001484,0.008724,0.006214,0.003706,0.001774,0.285481,0.859895,0.420234,180.827316,1000222046
1000222137,NaN,NaN,NaN,NaN,436.964447,56510.496094,37968.679688,11.268145,56510.390625,56511.085938,...,13.002812,0.101189,0.094573,0.087954,0.004679,0.049478,0.835397,0.300250,656.148987,1000222137
1000222184,NaN,NaN,NaN,NaN,280.326080,56928.988281,37485.148438,28.417866,56928.992188,56929.156250,...,58.057255,0.007953,0.007820,0.007687,0.000094,0.012023,0.773547,0.709031,300.273499,1000222184
1000222245,NaN,NaN,NaN,NaN,943.829407,56642.617188,37709.156250,19.873278,56642.761719,56642.667969,...,34.618137,0.012492,0.011468,0.010444,0.000724,0.063117,0.613272,0.507340,1304.447754,1000222245
1000222357,NaN,NaN,NaN,NaN,502.514038,56652.187500,37529.335938,17.657740,56652.140625,56653.218750,...,30.555212,0.002506,0.002506,0.002506,0.000000,0.000000,0.655908,1.000000,562.690552,1000222357

In [6]:
f2

,Track Ar1 Mean,Track Ar1 X,Track Ar1 Y,Track Ar1 Z,Track Area Mean,Track Center of Homogeneous Mass X,Track Center of Homogeneous Mass Y,Track Center of Homogeneous Mass Z,Track Center of Image Mass X Channel_1,Track Center of Image Mass X Channel_2,...,Track Shortest Distance to Surfaces Min_Surfaces Unnamed 4 CG.GC.C-.G-.icsx_[ibrx_2023-09-27T11-04-45.364],Track Speed Max,Track Speed Mean,Track Speed Min,Track Speed StdDev,Track Speed Variation,Track Sphericity Mean,Track Straightness,Track Volume Mean,Track_ID
1000000000,-0.550184,-0.591558,-0.706574,-0.352421,184.048630,57305.355469,38205.421875,38.931080,57305.492188,57305.222656,...,58.586376,0.041609,0.022603,0.010553,0.007755,0.343085,0.730995,0.027259,145.742294,1000000000
1000000001,-0.476468,-0.305364,-0.885106,-0.238933,173.122635,57245.156250,38255.199219,4.065064,57245.222656,57245.167969,...,81.714478,0.026032,0.021547,0.016280,0.003183,0.147718,0.785525,0.140231,149.012894,1000000001
1000000003,-0.451769,-0.417780,-0.491516,-0.446013,3441.188721,57338.707031,38082.734375,26.736328,57339.503906,57338.050781,...,22.588594,0.072173,0.027683,0.010563,0.011372,0.410796,0.426913,0.035962,5119.760742,1000000003
1000000005,0.461317,0.605533,0.359849,0.418570,340.100220,57337.539062,38049.863281,37.823231,57337.769531,57338.199219,...,7.265651,0.030330,0.019375,0.015690,0.005034,0.259816,0.641248,0.401058,328.207428,1000000005
1000000006,NaN,NaN,NaN,NaN,3731.450195,57325.714844,38074.410156,23.871647,57325.816406,57325.382812,...,19.686106,0.040204,0.033214,0.026096,0.004988,0.150175,0.381708,0.937294,5147.984375,1000000006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000222046,NaN,NaN,NaN,NaN,179.472153,56780.675781,37800.671875,39.741333,56780.726562,56780.429688,...,42.001484,0.008724,0.006214,0.003706,0.001774,0.285481,0.859895,0.420234,180.827316,1000222046
1000222137,NaN,NaN,NaN,NaN,436.964447,56510.496094,37968.679688,11.268145,56510.390625,56511.085938,...,13.002812,0.101189,0.094573,0.087954,0.004679,0.049478,0.835397,0.300250,656.148987,1000222137
1000222184,NaN,NaN,NaN,NaN,280.326080,56928.988281,37485.148438,28.417866,56928.992188,56929.156250,...,58.057255,0.007953,0.007820,0.007687,0.000094,0.012023,0.773547,0.709031,300.273499,1000222184
1000222245,NaN,NaN,NaN,NaN,943.829407,56642.617188,37709.156250,19.873278,56642.761719,56642.667969,...,34.618137,0.012492,0.011468,0.010444,0.000724,0.063117,0.613272,0.507340,1304.447754,1000222245
1000222357,NaN,NaN,NaN,NaN,502.514038,56652.187500,37529.335938,17.657740,56652.140625,56653.218750,...,30.555212,0.002506,0.002506,0.002506,0.000000,0.000000,0.655908,1.000000,562.690552,1000222357

In [ ]:
np.array(data.get("Scene8").get("Content").get("MegaSurfaces0").get("SurfaceModel"))

In [ ]:
np.array(data.get("Scene8").get("Content").get("MegaSurfaces0").get("TrackObject0"))

In [ ]:
object_ids = pd.DataFrame(np.asarray(data.get("Scene8").get("Content").get("MegaSurfaces0").get("TrackObject0")))
object_ids

In [ ]:
object_ids = pd.DataFrame(np.asarray(data.get("Scene8").get("Content").get("MegaSurfaces0").get("SurfaceModel")))
object_ids

In [ ]:
trackinfo = pd.DataFrame(np.asarray(data.get("Scene8").get("Content").get("MegaSurfaces0").get("Track0")))
trackinfo

In [ ]:
segments = pd.DataFrame(np.asarray(data.get("Scene8").get("Content").get("MegaSurfaces0").get("TrackEdge0")))
segments

In [ ]:
TrackSegment0

In [ ]:
out = parser.inspect(0)

In [ ]:
f = out["stats_df"]
f2 = out["stats_df2"]
f.equals(f2)